
/* C++ module generated by Quo C++ translator.
 * Timestamp: {{ ts }}
 */

#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <vector>

typedef int Int;
using ::std::string;
using ::std::vector;
using ::std::map;


template<typename T>
Int Print(const T& t) {
  ::std::cout << t;
  return 0;
}

template<typename T>
Int Println(const T& t) {
  Print(t);
  ::std::cout << ::std::endl;
  return 0;
}

{{ content }}

