;; Generated by quo stage 0
(module
  (import "env" "memory" (memory 256))
  (import "debug" "puts" (func $puts (param i32)))

  (func $load8_u (param $addr i32) (result i32)
    (i32.load8_u (local.get $addr)))
  (func $store8 (param $addr i32) (param $value i32)
    (i32.store8 (local.get $addr) (local.get $value)))

  (global $g (mut i32) (i32.const 0))
  (func $getAnswer (result i32)
    (return (i32.const 42))
  )
  (export "getAnswer" (func $getAnswer))
)